### ISSUE TITLE
Hope for English language support and multi-column csv data plotting 

### ISSUE THREAD

**Issue by ouening** [chrille69/Inkscape-Extension-xy-data-plot#1]
Hi, this project is awesome! And I hope it can be more actively developed

**Comment by ouening** [comment]
1. Using Google Translation I have translated German to English for myself.
2. I tried to add **font** setup for title and x,y labels:
(1) In `xy-data-plot.inx`, add
```
<param name="font_family" type="optiongroup" appearance="combo" gui-text="Font Family:">
        <option value="Times New Roman">Times New Roman</option>
        <option value="SimSun">宋体</option>
        <option value="sans-serif">sans-serif</option>
        <option value="Consolas">Consolas</option>
``` 
in **label page**;
(2) In `xy-data-plot.py`，add
`self.arg_parser.add_argument("--font_family", dest="font_family", type=str, action="store", default="Times New Roman")` in **line 219**
and 
`'font-family':self.options.font_family` in the **dict textstyle**

3. The last problem: Plotting more than one line in a same graph. 
I have 3 columns for my data, and I got the result below after excuted the program twice with different y columns:
![image](https://user-images.githubusercontent.com/15122811/81165841-46f4d080-8fc5-11ea-965c-694f99f97ffe.png)
clearly the y-range is not the same, and it's difficult to distinguish different plot (different color needed), I don't know how to perform it .

**Comment by chrille69** [comment]
I added multicolum support for x-values.

I will add the text-style specification later.

I did not understand, where to place language files for localization :-(

**Comment by chrille69** [comment]
Thank you for the text improvement. But i replaced the select box by a text field. So one can use a font installed on the system. It defaults to a standard font if the user put garbage into the text field. It's funny to use Algerian or Stencil.

I translated everthing in english.

I don't want to offer more style attribute like line-color, because one can easily go into the group, select the line and adjust the attributes in inkscape dialogs.

Thanks for the interest and the support.
